### ISSUE TITLE
Fix swipl version

### ISSUE THREAD

**Issue by sudhackar** [exercism/prolog-test-runner#27]
Continuing discussion from #26 

Right now
https://github.com/exercism/prolog-test-runner/blob/4de9281879a01aea7e62c34d65484744aecc17f7/Dockerfile#L7

We install the latest `swipl` from https://launchpad.net/~swi-prolog/+archive/ubuntu/stable
This could change the behaviour of `swipl` and the tests - expected output format might change. This was causing the build to fail in #26

We could fix this by settling on a specific `swipl` version and using that in the docker.

**Comment by sudhackar** [comment]
Another option is to use an official docker image from SWI-Prolog community - 
See https://hub.docker.com/_/swipl?tab=description

https://github.com/SWI-Prolog/docker-swipl/blob/master/8.4.2/bullseye/Dockerfile

**Comment by ErikSchierboom** [comment]
Closed by #28
